version: '3.8'

services:
  # Flask Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env.local
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        sleep 5 &&
        python reset_db.py --schema=supabase/migrations/local_schema.sql &&
        flask run --host=0.0.0.0
      "
    depends_on:
      - postgres

  # PostgreSQL Database with PostGIS
  postgres:
    image: postgis/postgis:14-3.3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI

volumes:
  postgres_data: