# Dockerfile.dev
FROM python:3.10-slim

WORKDIR /app

# Install additional dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy source code
COPY . .

# Expose port
EXPOSE 5000

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=development
ENV FLASK_APP=run.py
ENV FLASK_DEBUG=1

# Run the app
CMD ["flask", "run", "--host=0.0.0.0"]