# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: true  # Only for development/testing

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    # Uncomment for HTTP to HTTPS redirect
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ":443"

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: plumberleads_network
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Add ping for healthcheck
ping:
  entryPoint: web

# Configure certificate resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@example.com"  # Replace with your email
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

# Configure logs
log:
  level: "DEBUG"
  filePath: "/var/log/traefik/traefik.log"

# Configure access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100 