http:
  routers:
    # Router for the web application (HTTP - redirects to HTTPS)
    web-router:
      entryPoints:
        - web
      service: web-service
      rule: "PathPrefix(`/`)"
      priority: 1
    
    # Router for the web application (HTTPS)
    web-secure-router:
      entryPoints:
        - websecure
      service: web-service
      rule: "PathPrefix(`/`)"
      priority: 1
      tls:
        certResolver: letsencrypt
    
    # Router for the Traefik dashboard (HTTP - redirects to HTTPS)
    dashboard-router:
      entryPoints:
        - web
      service: api@internal
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      priority: 10
    
    # Router for the Traefik dashboard (HTTPS)
    dashboard-secure-router:
      entryPoints:
        - websecure
      service: api@internal
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      priority: 10
      tls:
        certResolver: letsencrypt
      middlewares:
        - dashboard-auth

  services:
    web-service:
      loadBalancer:
        servers:
          - url: "http://plumberleads-web:5000"
        passHostHeader: true

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$talBPKvT$1oJK1OyTVzlJva5T/XrpO/" 