entryPoints:
  web:
    address: ":80"
  
  # Keep websecure for future use, but we'll primarily use HTTP for development
  websecure:
    address: ":443"

# Configure a simple file provider for static configuration
providers:
  docker:
    exposedByDefault: false
    network: plumberleads_network
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Enable API and dashboard for debugging
api:
  dashboard: true
  insecure: true

# Add ping for healthcheck
ping:
  entryPoint: web

# Enable access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# Enable logs
log:
  level: "DEBUG"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-actual-email@yourdomain.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: false 