entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  
  # Keep websecure for future use, but we'll primarily use HTTP for development
  websecure:
    address: ":443"

# Configure a simple file provider for static configuration
providers:
  docker:
    exposedByDefault: false
    network: plumberleads_network
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Enable API and dashboard for debugging
api:
  dashboard: true
  # Access dashboard securely through HTTPS
  insecure: false

# Add ping for healthcheck
ping:
  entryPoint: web

# Enable access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# Enable logs
log:
  level: "DEBUG"
  filePath: "/var/log/traefik/traefik.log"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "your-email@example.com"  # Replace with your actual email
      storage: /acme.json
      httpChallenge:
        entryPoint: web